### ISSUE TITLE
help - AttributeError: module 'discord' has no attribute 'Intents'

### ISSUE THREAD

**Issue by Kzne** [atbrandt/DeadbearBot#6]
C:\Users\kcros\Desktop\DeadbearBot-master>python main.py
Traceback (most recent call last):
  File "C:\Users\kcros\Desktop\DeadbearBot-master\main.py", line 42, in <module>
    intents = discord.Intents.all()
AttributeError: module 'discord' has no attribute 'Intents'

**Comment by atbrandt** [comment]
Hey there!

"Intents" are a new feature/requirement of the Discord API and the Discord.py library. You can fix this issue by updating your installation of Discord.py to the latest version via console with `py -3 -m pip install -U discord.py`. More info can be found here if you're curious: https://discordpy.readthedocs.io/en/latest/intents.html#intents-primer
